---
resolved_ips:
  192.168.50.21:
    names: [istio1]
  192.168.50.22:
    names: [istio2]
  192.168.50.23:
    names: [istio3]

kube_users:
  - vagrant
kubectl_conf_path: /etc/kubernetes/admin.conf

kube_version: v1.6.6
kube_conf_dir: /etc/kubernetes
# kube_cert_dir: "{{ kube_conf_dir }}/certs"
kube_manifest_dir: "{{ kube_conf_dir }}/manifests"
kube_master_api_port: 8080
kube_master_host: "{{ groups['kube-master'][0] }}"
# kube_api_endpoint: "http://{{ kube_master_host }}:{{ kube_master_api_port }}"
kubeadm_token: abcdef.ghijklmnopqrstuv
# Kubernetes internal network for services.
# Kubernetes services will get fake IP addresses from this range.
# This range must not conflict with anything in your infrastructure. These
# addresses do not need to be routable and must just be an unused block of space.
kube_service_cidr: 10.254.0.0/16
# kube_service_api_ip: 10.254.0.1
# kube_dns_ip: 10.254.254.254
# If you specify domain you must change /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
# kube_dns_domain: cluster.local
