---
- name: Get helm package
  unarchive:
    src: "{{ helm_pkg_url }}"
    dest: /tmp
    remote_src: yes
  become: yes

- name: Copy helm bin to /usr/local/bin
  shell: cp /tmp/linux-amd64/helm /usr/local/bin/helm && chmod 755 /usr/local/bin/helm
  args:
    creates: /usr/local/bin/helm
  become: yes

- name: Initialize helm
  command: helm init
  environment:
    KUBECONFIG: "{{ kubectl_conf_path }}"
  become: yes
