---
# TODO remove getIstio script dpendency
- name: Install istio
  shell: curl -L https://git.io/getIstio | sh -
  args: 
    chdir: /opt
    creates: "{{ istio_pkg_dir }}"
  become: yes

- name: Set PATH to istio binaries
  template:
    src: istio.sh.j2
    dest: /etc/profile.d/istio.sh
  become: yes

- name: Setup RBAC
  kubectl:
    action: present
    filepath: "{{ item }}"
  environment:
    KUBECONFIG: "{{ kubectl_conf_path }}"
  with_items:
    - "{{ istio_pkg_dir }}/install/kubernetes/istio-rbac-beta.yaml"
    - "{{ istio_pkg_dir }}/install/kubernetes/istio.yaml"
    - "{{ istio_pkg_dir }}/install/kubernetes/addons/prometheus.yaml"
    - "{{ istio_pkg_dir }}/install/kubernetes/addons/grafana.yaml"
    - "{{ istio_pkg_dir }}/install/kubernetes/addons/zipkin.yaml"
  become: yes
