---
- name: Check if already installed
  stat:
    path: /etc/kubernetes/pki
  register: ca

  # TODO: remove --skip-preflight-checks flag if issue 347 is fixed.
  # ref. https://github.com/kubernetes/kubeadm/issues/347
- block:
    - name: kubeadam join
      shell: >
        kubeadm join
        --token={{ kubeadm_token }}
        {{ kube_master_host }}:{{ kube_master_api_port }}
        --skip-preflight-checks
      become: yes
      register: output

    - debug: msg={{ output.stdout_lines }}
  when: ca.stat.isdir is not defined
